[package]
name = "pointercrate-user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pointercrate-core = {path = "../pointercrate-core"}
serde = "1.0.118"
derive_more = "0.99.11"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono", "offline" ] }
jsonwebtoken = "7.2.0"
log = "0.4.11"
futures = "0.3.8"
base64 = "0.13.0"
lazy_static = "1.4.0"
bcrypt = "0.9.0"
url = "2.2.0"
serde_json = "1.0.60"
