version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 1
    groups:
      pointercrate:
        patterns:
          - "*"
