[package]
name = "pointercrate-integrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sqlx = { version = "0.6", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono", "offline" ] }
bincode = "1.3.1"
reqwest = "0.11.*"
futures = "0.3.8"
log = "0.4.11"
chrono = "0.4.19"
tokio = {version = "1.20.4", features = ["rt"]}

[dependencies.dash-rs]
git = "https://github.com/qimiko/dash-rs"
