[package]
name = "pointercrate-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.118"
derive_more = "0.99.11"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono" ] }
log = "0.4.8"
chrono = {version = "0.4.19", features = ["serde"]}
