[package]
name = "pointercrate-demonlist-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
pointercrate-demonlist = {path = "../pointercrate-demonlist"}
pointercrate-demonlist-pages = {path = "../pointercrate-demonlist-pages"}
pointercrate-core = {path = "../pointercrate-core"}
pointercrate-core-api = {path = "../pointercrate-core-api"}
pointercrate-user = {path = "../pointercrate-user"}
pointercrate-user-api = {path = "../pointercrate-user-api"}
pointercrate-integrate = {path = "../pointercrate-integrate"}
sqlx = { version = "0.5", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono", "offline" ] }
serde_json = "1.0.60"
log = "0.4.11"
serde_urlencoded = "0.7.0"
ratelimit_meter = "5.0.0"
nonzero_ext = "0.2.0"
reqwest = {version = "0.11.*", features = ["json"]}
chrono = "0.4.19"
serde = "1.0.118"
