[package]
name = "pointercrate-core-pages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.25"
pointercrate-core = {path = "../pointercrate-core"}
